WITH T_ORDERS AS
(
 O_ORDERKEY AS order_id,
 O_CUSTKEY AS customer_id,
 O_ORDERSTATUS AS STATUS,
 O_TOTALPRICE AS PRICE,
 O_ORDERDATE AS ORDER_DATE
 from CTEPL.HPN.ORDERS
)
SELECT * FROM T_ORDERS
ORDER BY order_id
